---
abstract: 'An authentication module for Salesforce OAuth 2.'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  Data::UUID: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IO::Socket::SSL: '0'
  IPC::Open3: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::NoTabs: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Salesforce
requires:
  Digest::SHA: '0'
  Mojo::Base: '0'
  Mojo::Parameters: '0'
  Mojo::URL: '0'
  Mojo::UserAgent: '0'
resources:
  homepage: https://github.com/battlemidget/p5-net-salesforce
  repository: https://github.com/battlemidget/p5-net-salesforce.git
version: '1.101'
x_authority: cpan:ADAMJS
