---
abstract: 'Authentication against Salesforce OAuth 2 endpoints.'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Salesforce
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Digest::SHA: 0
  Mojo::Base: 0
  Mojo::Parameters: 0
  Mojo::URL: 0
  Mojo::UserAgent: 0
  Mojolicious::Lite: 0
resources:
  bugtracker: https://github.com/battlemidget/Net-Salesforce/issues
  homepage: https://github.com/battlemidget/Net-Salesforce
  repository: https://github.com/battlemidget/Net-Salesforce.git
version: 0.02
x_contributors:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
